server:
  port: ${PORT:8080}

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Tokyo
app:
  order-storage:
    path: ${ORDER_STORAGE_PATH:./data/orders.txt}

